### ISSUE TITLE
how to use it ?

### ISSUE THREAD

**Issue by ALANHXR** [Alex-neko/SAS#1]
i am using sublime3.And i want that it can help me on typing sas code.
I found out your code.And i can't found out how to use it.

**Comment by Alex-neko** [comment]
Just put the things in a folder (you can name it 'sas'), in the packages folder of your ST3 installation (ie Application Support ▸ Sublime Text 3 ▸ Packages on OsX).

But this is a little thing i wrote months ago and it is incomplete. No support is provided.

**Comment by ALANHXR** [comment]
My system is windows.Do you know how to installation this cool thing in windows?

**Comment by Alex-neko** [comment]
It seems to be in ST installation folder /Data/Packages/

**Comment by ALANHXR** [comment]
done! Thanks so much!
